// Keyboard layout definitions
import type { KeyboardLayout } from '@/types/Settings';

export interface KeyDefinition {
    key: string;
    display: string;
    width?: number;
}

export type KeyboardLayoutDefinition = KeyDefinition[][];

export const KEYBOARD_LAYOUTS: Record<KeyboardLayout, KeyboardLayoutDefinition> =
{
    qwerty: [
        [
            { key: '`', display: '`' },
            { key: '1', display: '1' },
            { key: '2', display: '2' },
            { key: '3', display: '3' },
            { key: '4', display: '4' },
            { key: '5', display: '5' },
            { key: '6', display: '6' },
            { key: '7', display: '7' },
            { key: '8', display: '8' },
            { key: '9', display: '9' },
            { key: '0', display: '0' },
            { key: '-', display: '-' },
            { key: '=', display: '=' },
            { key: 'Backspace', display: '⌫', width: 2 },
        ],
        [
            { key: 'Tab', display: 'Tab', width: 1.5 },
            { key: 'q', display: 'Q' },
            { key: 'w', display: 'W' },
            { key: 'e', display: 'E' },
            { key: 'r', display: 'R' },
            { key: 't', display: 'T' },
            { key: 'y', display: 'Y' },
            { key: 'u', display: 'U' },
            { key: 'i', display: 'I' },
            { key: 'o', display: 'O' },
            { key: 'p', display: 'P' },
            { key: '[', display: '[' },
            { key: ']', display: ']' },
            { key: '\\', display: '\\', width: 1.5 },
        ],
        [
            { key: 'CapsLock', display: 'Caps', width: 1.75 },
            { key: 'a', display: 'A' },
            { key: 's', display: 'S' },
            { key: 'd', display: 'D' },
            { key: 'f', display: 'F' },
            { key: 'g', display: 'G' },
            { key: 'h', display: 'H' },
            { key: 'j', display: 'J' },
            { key: 'k', display: 'K' },
            { key: 'l', display: 'L' },
            { key: ';', display: ';' },
            { key: "'", display: "'" },
            { key: 'Enter', display: '↵', width: 2.25 },
        ],
        [
            { key: 'Shift', display: 'Shift', width: 2.25 },
            { key: 'z', display: 'Z' },
            { key: 'x', display: 'X' },
            { key: 'c', display: 'C' },
            { key: 'v', display: 'V' },
            { key: 'b', display: 'B' },
            { key: 'n', display: 'N' },
            { key: 'm', display: 'M' },
            { key: ',', display: ',' },
            { key: '.', display: '.' },
            { key: '/', display: '/' },
            { key: 'Shift', display: 'Shift', width: 2.75 },
        ],
        [
            { key: ' ', display: 'Space', width: 6 },
        ],
    ],
    dvorak: [
        [
            { key: '`', display: '`' },
            { key: '1', display: '1' },
            { key: '2', display: '2' },
            { key: '3', display: '3' },
            { key: '4', display: '4' },
            { key: '5', display: '5' },
            { key: '6', display: '6' },
            { key: '7', display: '7' },
            { key: '8', display: '8' },
            { key: '9', display: '9' },
            { key: '0', display: '0' },
            { key: '[', display: '[' },
            { key: ']', display: ']' },
            { key: 'Backspace', display: '⌫', width: 2 },
        ],
        [
            { key: 'Tab', display: 'Tab', width: 1.5 },
            { key: "'", display: "'" },
            { key: ',', display: ',' },
            { key: '.', display: '.' },
            { key: 'p', display: 'P' },
            { key: 'y', display: 'Y' },
            { key: 'f', display: 'F' },
            { key: 'g', display: 'G' },
            { key: 'c', display: 'C' },
            { key: 'r', display: 'R' },
            { key: 'l', display: 'L' },
            { key: '/', display: '/' },
            { key: '=', display: '=' },
            { key: '\\', display: '\\', width: 1.5 },
        ],
        [
            { key: 'CapsLock', display: 'Caps', width: 1.75 },
            { key: 'a', display: 'A' },
            { key: 'o', display: 'O' },
            { key: 'e', display: 'E' },
            { key: 'u', display: 'U' },
            { key: 'i', display: 'I' },
            { key: 'd', display: 'D' },
            { key: 'h', display: 'H' },
            { key: 't', display: 'T' },
            { key: 'n', display: 'N' },
            { key: 's', display: 'S' },
            { key: '-', display: '-' },
            { key: 'Enter', display: '↵', width: 2.25 },
        ],
        [
            { key: 'Shift', display: 'Shift', width: 2.25 },
            { key: ';', display: ';' },
            { key: 'q', display: 'Q' },
            { key: 'j', display: 'J' },
            { key: 'k', display: 'K' },
            { key: 'x', display: 'X' },
            { key: 'b', display: 'B' },
            { key: 'm', display: 'M' },
            { key: 'w', display: 'W' },
            { key: 'v', display: 'V' },
            { key: 'z', display: 'Z' },
            { key: 'Shift', display: 'Shift', width: 2.75 },
        ],
        [
            { key: ' ', display: 'Space', width: 6 },
        ],
    ],
    colemak: [
        [
            { key: '`', display: '`' },
            { key: '1', display: '1' },
            { key: '2', display: '2' },
            { key: '3', display: '3' },
            { key: '4', display: '4' },
            { key: '5', display: '5' },
            { key: '6', display: '6' },
            { key: '7', display: '7' },
            { key: '8', display: '8' },
            { key: '9', display: '9' },
            { key: '0', display: '0' },
            { key: '-', display: '-' },
            { key: '=', display: '=' },
            { key: 'Backspace', display: '⌫', width: 2 },
        ],
        [
            { key: 'Tab', display: 'Tab', width: 1.5 },
            { key: 'q', display: 'Q' },
            { key: 'w', display: 'W' },
            { key: 'f', display: 'F' },
            { key: 'p', display: 'P' },
            { key: 'g', display: 'G' },
            { key: 'j', display: 'J' },
            { key: 'l', display: 'L' },
            { key: 'u', display: 'U' },
            { key: 'y', display: 'Y' },
            { key: ';', display: ';' },
            { key: '[', display: '[' },
            { key: ']', display: ']' },
            { key: '\\', display: '\\', width: 1.5 },
        ],
        [
            { key: 'CapsLock', display: 'Caps', width: 1.75 },
            { key: 'a', display: 'A' },
            { key: 'r', display: 'R' },
            { key: 's', display: 'S' },
            { key: 't', display: 'T' },
            { key: 'd', display: 'D' },
            { key: 'h', display: 'H' },
            { key: 'n', display: 'N' },
            { key: 'e', display: 'E' },
            { key: 'i', display: 'I' },
            { key: 'o', display: 'O' },
            { key: "'", display: "'" },
            { key: 'Enter', display: '↵', width: 2.25 },
        ],
        [
            { key: 'Shift', display: 'Shift', width: 2.25 },
            { key: 'z', display: 'Z' },
            { key: 'x', display: 'X' },
            { key: 'c', display: 'C' },
            { key: 'v', display: 'V' },
            { key: 'b', display: 'B' },
            { key: 'k', display: 'K' },
            { key: 'm', display: 'M' },
            { key: ',', display: ',' },
            { key: '.', display: '.' },
            { key: '/', display: '/' },
            { key: 'Shift', display: 'Shift', width: 2.75 },
        ],
        [
            { key: ' ', display: 'Space', width: 6 },
        ],
    ],
};
